export const adminManageTask = [
	{
		id: 3457,
		name: "Gbenga Akinnukawe",
		email: "akinu@gmail.com",
		message: "Your product have been sent to the farmer",
		status: "In review",
		tbcName: "admin-general-tbody",
		tbcIcon: "styletableicon",
	},
	{
		id: 7897,
		name: "Nneoma Raymond",
		email: "nenne@gmail.com",
		message: "The product sent is pending",
		status: "In review",
		tbcName: "admin-general-tbody",
		tbcIcon: "styletableicon",
	},
	{
		id: 5587,
		name: "Chukwuebuka Victor",
		email: "ebus@gmail.com",
		message: "The product sent is pending",
		status: "Completed",
		tbcName: "admin-general-tbody",
		tbcIcon: "styletableicon",
	},
	{
		id: 7587,
		name: "Cynthia Nwankwo",
		email: "nwacynti@gmail.com",
		message: "Your product have been sent to the farmer",
		status: "In review",
		tbcName: "admin-general-tbody",
		tbcIcon: "styletableicon",
	},
];

export const adminLogistics = [
	{
		id: 1234,
		name: "Godswill Chibuzor",
		account: "1234567890",
		ccv: "123",
		balance: "25000",
		date: "12/10/2022",
		status: "Succesful",
		action: "Notify",
	},
	{
		id: 1234,
		name: "Godswill Chibuzor",
		account: "1234567890",
		ccv: "123",
		balance: "25000",
		date: "12/10/2022",
		status: "Succesful",
		action: "Notify",
	},
	{
		id: 1234,
		name: "Godswill Chibuzor",
		account: "1234567890",
		ccv: "123",
		balance: "25000",
		date: "12/10/2022",
		status: "Succesful",
		action: "Notify",
	},
	{
		id: 1234,
		name: "Godswill Chibuzor",
		account: "1234567890",
		ccv: "123",
		balance: "25000",
		date: "12/10/2022",
		status: "Succesful",
		action: "Notify",
	},
];
